"""initial schema

Revision ID: 1c11ddc24b61
Revises: 
Create Date: 2026-08-01 14:20:15.831287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c11ddc24b61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadchanim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('female_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shadchan_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shadchan_id'], ['shadchanim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('male_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shadchan_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shadchan_id'], ['shadchanim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('female_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('female_candidate_id', sa.Integer(), nullable=False),
    sa.Column('institution_type', sa.Enum('BEIT_YAAKOV', 'SEMINAR', 'MASLUL', name='female_institution_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('female_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('female_candidate_id', sa.Integer(), nullable=False),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('mother_name', sa.String(length=200), nullable=True),
    sa.Column('mother_maiden_name', sa.String(length=200), nullable=True),
    sa.Column('father_occupation', sa.String(length=200), nullable=True),
    sa.Column('mother_occupation', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('female_candidate_id')
    )
    op.create_table('female_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('female_candidate_id', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.Enum('RABBI_TEACHER', 'FRIEND', 'FAMILY', name='reference_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role_connection', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('female_siblings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('female_candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('male_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_candidate_id', sa.Integer(), nullable=False),
    sa.Column('institution_type', sa.Enum('TALMUD_TORAH', 'YESHIVA_KETANA', 'YESHIVA_GEDOLA', name='male_institution_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('male_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_candidate_id', sa.Integer(), nullable=False),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('mother_name', sa.String(length=200), nullable=True),
    sa.Column('mother_maiden_name', sa.String(length=200), nullable=True),
    sa.Column('father_occupation', sa.String(length=200), nullable=True),
    sa.Column('mother_occupation', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('male_candidate_id')
    )
    op.create_table('male_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_candidate_id', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.Enum('RABBI_TEACHER', 'FRIEND', 'FAMILY', name='reference_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role_connection', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('male_siblings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('male_siblings')
    op.drop_table('male_references')
    op.drop_table('male_parents')
    op.drop_table('male_education')
    op.drop_table('female_siblings')
    op.drop_table('female_references')
    op.drop_table('female_parents')
    op.drop_table('female_education')
    op.drop_table('male_candidates')
    op.drop_table('female_candidates')
    op.drop_table('shadchanim')
    # ### end Alembic commands ###
