"""flatten education into candidate columns

Revision ID: b0dfb81c10f8
Revises: 1c11ddc24b61
Create Date: 2026-08-01 15:12:04.384744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0dfb81c10f8'
down_revision: Union[str, Sequence[str], None] = '1c11ddc24b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('female_education')
    op.drop_table('male_education')
    # dropping the tables above does not drop the Postgres enum types they used
    op.execute('DROP TYPE IF EXISTS male_institution_type')
    op.execute('DROP TYPE IF EXISTS female_institution_type')
    op.add_column('female_candidates', sa.Column('beit_yaakov', sa.String(length=200), nullable=True))
    op.add_column('female_candidates', sa.Column('seminar', sa.String(length=200), nullable=True))
    op.add_column('female_candidates', sa.Column('maslul', sa.String(length=200), nullable=True))
    op.add_column('male_candidates', sa.Column('talmud_torah', sa.String(length=200), nullable=True))
    op.add_column('male_candidates', sa.Column('yeshiva_ketana', sa.String(length=200), nullable=True))
    op.add_column('male_candidates', sa.Column('yeshiva_gedola', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('male_candidates', 'yeshiva_gedola')
    op.drop_column('male_candidates', 'yeshiva_ketana')
    op.drop_column('male_candidates', 'talmud_torah')
    op.drop_column('female_candidates', 'maslul')
    op.drop_column('female_candidates', 'seminar')
    op.drop_column('female_candidates', 'beit_yaakov')
    op.create_table('male_education',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('male_candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('institution_type', postgresql.ENUM('TALMUD_TORAH', 'YESHIVA_KETANA', 'YESHIVA_GEDOLA', name='male_institution_type'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], name=op.f('male_education_male_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('male_education_pkey'))
    )
    op.create_table('female_education',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('female_candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('institution_type', postgresql.ENUM('BEIT_YAAKOV', 'SEMINAR', 'MASLUL', name='female_institution_type'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], name=op.f('female_education_female_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('female_education_pkey'))
    )
    # ### end Alembic commands ###
