"""add favourites and notes to candidates

Revision ID: b82e29327e7b
Revises: b29eb184fccf
Create Date: 2026-08-24 19:01:05.286270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82e29327e7b'
down_revision: Union[str, Sequence[str], None] = 'b29eb184fccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('female_candidates', sa.Column('is_favourite', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('female_candidates', sa.Column('notes', sa.String(length=2000), nullable=True))
    op.add_column('male_candidates', sa.Column('is_favourite', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('male_candidates', sa.Column('notes', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('male_candidates', 'notes')
    op.drop_column('male_candidates', 'is_favourite')
    op.drop_column('female_candidates', 'notes')
    op.drop_column('female_candidates', 'is_favourite')
    # ### end Alembic commands ###
