"""merge parents and siblings into relatives, unify references across gender

Revision ID: b983e2e1f950
Revises: b0dfb81c10f8
Create Date: 2026-08-01 16:27:47.194810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b983e2e1f950'
down_revision: Union[str, Sequence[str], None] = 'b0dfb81c10f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_candidate_id', sa.Integer(), nullable=True),
    sa.Column('female_candidate_id', sa.Integer(), nullable=True),
    sa.Column(
        'ref_type',
        postgresql.ENUM('RABBI_TEACHER', 'FRIEND', 'FAMILY', name='reference_type', create_type=False),
        nullable=False,
    ),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role_connection', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(male_candidate_id IS NOT NULL AND female_candidate_id IS NULL) OR (male_candidate_id IS NULL AND female_candidate_id IS NOT NULL)', name='ck_candidate_references_exactly_one_candidate'),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], ),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_candidate_id', sa.Integer(), nullable=True),
    sa.Column('female_candidate_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.Enum('FATHER', 'MOTHER', 'SIBLING', name='relation_type'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('maiden_name', sa.String(length=200), nullable=True),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(male_candidate_id IS NOT NULL AND female_candidate_id IS NULL) OR (male_candidate_id IS NULL AND female_candidate_id IS NOT NULL)', name='ck_relatives_exactly_one_candidate'),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], ),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('male_parents')
    op.drop_table('male_references')
    op.drop_table('female_parents')
    op.drop_table('female_references')
    op.drop_table('male_siblings')
    op.drop_table('female_siblings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('female_siblings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('female_candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], name=op.f('female_siblings_female_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('female_siblings_pkey'))
    )
    op.create_table('male_siblings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('male_candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], name=op.f('male_siblings_male_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('male_siblings_pkey'))
    )
    op.create_table('female_references',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('female_candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(
        'ref_type',
        postgresql.ENUM('RABBI_TEACHER', 'FRIEND', 'FAMILY', name='reference_type', create_type=False),
        autoincrement=False, nullable=False,
    ),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role_connection', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], name=op.f('female_references_female_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('female_references_pkey'))
    )
    op.create_table('female_parents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('female_candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('father_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('mother_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('mother_maiden_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('father_occupation', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('mother_occupation', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['female_candidate_id'], ['female_candidates.id'], name=op.f('female_parents_female_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('female_parents_pkey')),
    sa.UniqueConstraint('female_candidate_id', name=op.f('female_parents_female_candidate_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('male_references',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('male_candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(
        'ref_type',
        postgresql.ENUM('RABBI_TEACHER', 'FRIEND', 'FAMILY', name='reference_type', create_type=False),
        autoincrement=False, nullable=False,
    ),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role_connection', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], name=op.f('male_references_male_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('male_references_pkey'))
    )
    op.create_table('male_parents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('male_candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('father_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('mother_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('mother_maiden_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('father_occupation', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('mother_occupation', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['male_candidate_id'], ['male_candidates.id'], name=op.f('male_parents_male_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('male_parents_pkey')),
    sa.UniqueConstraint('male_candidate_id', name=op.f('male_parents_male_candidate_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('relatives')
    op.drop_table('candidate_references')
    # relation_type is only used by 'relatives', now dropped - clean up the orphaned type
    op.execute('DROP TYPE IF EXISTS relation_type')
    # ### end Alembic commands ###
