"""add picture_url to candidates

Revision ID: fdc5c8385f41
Revises: b983e2e1f950
Create Date: 2026-08-08 11:36:03.504215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc5c8385f41'
down_revision: Union[str, Sequence[str], None] = 'b983e2e1f950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('female_candidates', sa.Column('picture_url', sa.String(length=500), nullable=True))
    op.add_column('male_candidates', sa.Column('picture_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('male_candidates', 'picture_url')
    op.drop_column('female_candidates', 'picture_url')
    # ### end Alembic commands ###
